apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrok
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngrok
  template:
    metadata:
      labels:
        app: ngrok
    spec:
      containers:
        - name: ngrok
          image: ngrok/ngrok:latest
          # Points directly to your internal K8s Service name
          args: ["http", "--domain=$(NGROK_DOMAIN)", "notification-service:8080"]
          envFrom:
            - secretRef:
                name: notification-env-secret
          ports:
            - containerPort: 4040
---
# Expose the Ngrok Dashboard (http://localhost:30040)
apiVersion: v1
kind: Service
metadata:
  name: ngrok-dashboard
spec:
  type: NodePort
  selector:
    app: ngrok
  ports:
    - port: 4040
      targetPort: 4040
      nodePort: 30040