# config/prometheus.yml
global:
  scrape_interval: 5s # Scrape often for dev testing

scrape_configs:
  - job_name: 'notification-service'
    metrics_path: '/q/metrics'
    static_configs:
      # 'app' matches the service name in your docker-compose.yaml
      - targets: ['app:8080']